import type {
  Accolade,
  Game,
  LeagueLink,
  NewsPost,
  Player,
  Season,
  SiteData,
  StaffMember,
  Team,
} from './league-types';

export const demoSeasons: Season[] = [
  {
    id: 'season-2026',
    slug: 'season-2026',
    name: 'Season 2026',
    isCurrent: true,
    startsOn: '2026-06-06',
    endsOn: '2026-09-20',
  },
  {
    id: 'season-2025',
    slug: 'season-2025',
    name: 'Season 2025',
    isCurrent: false,
    startsOn: '2025-06-01',
    endsOn: '2025-09-14',
  },
];

export const demoTeams: Team[] = [
  {
    id: 'bangkok-blaze',
    slug: 'bangkok-blaze',
    name: 'Bangkok Blaze',
    shortName: 'Blaze',
    abbreviation: 'BBZ',
    city: 'Bangkok',
    conference: 'East',
    primaryColor: '#ff6b22',
    secondaryColor: '#ffb067',
    wins: 8,
    losses: 2,
    description: 'Fast-paced basketball built around pressure defense and transition scoring.',
  },
  {
    id: 'chiang-mai-cloud',
    slug: 'chiang-mai-cloud',
    name: 'Chiang Mai Cloud',
    shortName: 'Cloud',
    abbreviation: 'CMC',
    city: 'Chiang Mai',
    conference: 'East',
    primaryColor: '#63d5ff',
    secondaryColor: '#d9f6ff',
    wins: 7,
    losses: 3,
    description: 'A disciplined two-way team with elite ball movement and spacing.',
  },
  {
    id: 'khon-kaen-kings',
    slug: 'khon-kaen-kings',
    name: 'Khon Kaen Kings',
    shortName: 'Kings',
    abbreviation: 'KKG',
    city: 'Khon Kaen',
    conference: 'East',
    primaryColor: '#ffcf43',
    secondaryColor: '#fff1a8',
    wins: 5,
    losses: 5,
    description: 'Physical rebounding and half-court execution define the Kings identity.',
  },
  {
    id: 'korat-thunder',
    slug: 'korat-thunder',
    name: 'Korat Thunder',
    shortName: 'Thunder',
    abbreviation: 'KRT',
    city: 'Nakhon Ratchasima',
    conference: 'East',
    primaryColor: '#8f7cff',
    secondaryColor: '#d8d1ff',
    wins: 3,
    losses: 7,
    description: 'Young, fearless and always ready to turn a game with a scoring run.',
  },
  {
    id: 'phuket-waves',
    slug: 'phuket-waves',
    name: 'Phuket Waves',
    shortName: 'Waves',
    abbreviation: 'PKW',
    city: 'Phuket',
    conference: 'West',
    primaryColor: '#00cfa6',
    secondaryColor: '#8cf8dd',
    wins: 9,
    losses: 1,
    description: 'Creative guard play and relentless tempo power the league leaders.',
  },
  {
    id: 'pattaya-pulse',
    slug: 'pattaya-pulse',
    name: 'Pattaya Pulse',
    shortName: 'Pulse',
    abbreviation: 'PTP',
    city: 'Pattaya',
    conference: 'West',
    primaryColor: '#ff4f91',
    secondaryColor: '#ffb1cf',
    wins: 6,
    losses: 4,
    description: 'A versatile roster that switches everything and attacks mismatches.',
  },
  {
    id: 'hat-yai-hawks',
    slug: 'hat-yai-hawks',
    name: 'Hat Yai Hawks',
    shortName: 'Hawks',
    abbreviation: 'HYH',
    city: 'Hat Yai',
    conference: 'West',
    primaryColor: '#ef3e46',
    secondaryColor: '#ff9b9f',
    wins: 4,
    losses: 6,
    description: 'A hard-nosed defensive group that thrives in close games.',
  },
  {
    id: 'rayong-raptors',
    slug: 'rayong-raptors',
    name: 'Rayong Raptors',
    shortName: 'Raptors',
    abbreviation: 'RYR',
    city: 'Rayong',
    conference: 'West',
    primaryColor: '#4a7dff',
    secondaryColor: '#a8bfff',
    wins: 2,
    losses: 8,
    description: 'A developing team with confident shooters and a strong community.',
  },
];

const baseStats = {
  gamesPlayed: 10,
  pointsPerGame: 15,
  reboundsPerGame: 5,
  assistsPerGame: 4,
  stealsPerGame: 1,
  blocksPerGame: 0.5,
  fieldGoalPct: 46,
  threePointPct: 35,
};

export const demoPlayers: Player[] = [
  ['kai-nova', 'Kai Nova', 'KaiNova24', 24, 'SG', 'bangkok-blaze', 28.4, 5.2, 4.8, 1.9, 0.4, 51.2, 42.8],
  ['mint-velocity', 'Mint Velocity', 'MintVelo', 3, 'PG', 'bangkok-blaze', 18.7, 3.8, 9.6, 2.3, 0.2, 47.6, 38.1],
  ['north-zen', 'North Zen', 'NorthZen', 11, 'PG', 'chiang-mai-cloud', 24.9, 4.1, 8.2, 1.7, 0.1, 49.1, 40.5],
  ['cloud-nine', 'Cloud Nine', 'CloudNineTH', 9, 'SF', 'chiang-mai-cloud', 19.5, 7.8, 3.2, 1.4, 0.8, 48.3, 36.7],
  ['king-krit', 'King Krit', 'KritTheKing', 0, 'PF', 'khon-kaen-kings', 21.2, 11.7, 2.9, 1.1, 1.6, 54.4, 31.2],
  ['mork-mamba', 'Mork Mamba', 'MorkMamba', 8, 'SG', 'khon-kaen-kings', 17.8, 4.9, 4.3, 1.2, 0.3, 45.2, 37.9],
  ['storm-sak', 'Storm Sak', 'StormSak', 7, 'SG', 'korat-thunder', 22.6, 4.7, 5.6, 1.8, 0.5, 46.8, 39.3],
  ['big-ton', 'Big Ton', 'BigTonCenter', 55, 'C', 'korat-thunder', 13.1, 12.4, 1.7, 0.7, 2.2, 57.1, 18.0],
  ['wave-rin', 'Wave Rin', 'WaveRin', 1, 'PG', 'phuket-waves', 26.1, 4.4, 10.2, 2.5, 0.2, 52.0, 41.6],
  ['ocean-max', 'Ocean Max', 'OceanMaxx', 32, 'C', 'phuket-waves', 20.4, 13.6, 2.1, 1.0, 2.7, 59.3, 28.4],
  ['pulse-pat', 'Pulse Pat', 'PulsePat', 13, 'SF', 'pattaya-pulse', 23.5, 8.1, 5.0, 1.6, 0.9, 50.4, 39.8],
  ['neon-nan', 'Neon Nan', 'NeonNan', 5, 'PG', 'pattaya-pulse', 16.9, 3.3, 7.7, 2.0, 0.1, 44.8, 36.2],
  ['hawk-him', 'Hawk Him', 'HawkHim', 21, 'PF', 'hat-yai-hawks', 19.8, 10.9, 3.0, 1.3, 1.9, 53.6, 33.0],
  ['south-sky', 'South Sky', 'SouthSkyy', 4, 'SG', 'hat-yai-hawks', 18.2, 4.0, 4.7, 1.5, 0.4, 47.0, 38.6],
  ['ray-rush', 'Ray Rush', 'RayRush', 10, 'PG', 'rayong-raptors', 20.7, 3.9, 6.8, 1.9, 0.1, 45.6, 37.4],
  ['raptor-tee', 'Raptor Tee', 'RaptorTee', 33, 'C', 'rayong-raptors', 14.6, 11.3, 1.8, 0.8, 2.0, 55.0, 24.5],
].map((row, index) => {
  const [slug, displayName, robloxUsername, jerseyNumber, position, teamId, ppg, rpg, apg, spg, bpg, fg, three] = row as [
    string,
    string,
    string,
    number,
    string,
    string,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ];

  return {
    id: slug,
    slug,
    displayName,
    robloxUsername,
    jerseyNumber,
    position,
    teamId,
    bio: `${displayName} brings pace, communication and competitive energy to every PBL matchup.`,
    isActive: true,
    stats: {
      ...baseStats,
      gamesPlayed: index % 5 === 0 ? 9 : 10,
      pointsPerGame: ppg,
      reboundsPerGame: rpg,
      assistsPerGame: apg,
      stealsPerGame: spg,
      blocksPerGame: bpg,
      fieldGoalPct: fg,
      threePointPct: three,
    },
  } satisfies Player;
});

export const demoGames: Game[] = [
  {
    id: 'game-101',
    slug: 'bbz-vs-cmc-week-6',
    seasonId: 'season-2026',
    week: 6,
    startsAt: '2026-07-29T13:00:00.000Z',
    status: 'scheduled',
    venue: 'PBL Arena 1',
    homeTeamId: 'bangkok-blaze',
    awayTeamId: 'chiang-mai-cloud',
    homeScore: null,
    awayScore: null,
    streamUrl: 'https://www.youtube.com/',
  },
  {
    id: 'game-102',
    slug: 'pkw-vs-ptp-week-6',
    seasonId: 'season-2026',
    week: 6,
    startsAt: '2026-07-30T13:30:00.000Z',
    status: 'scheduled',
    venue: 'PBL Arena 2',
    homeTeamId: 'phuket-waves',
    awayTeamId: 'pattaya-pulse',
    homeScore: null,
    awayScore: null,
    streamUrl: 'https://www.youtube.com/',
  },
  {
    id: 'game-103',
    slug: 'kkg-vs-krt-week-6',
    seasonId: 'season-2026',
    week: 6,
    startsAt: '2026-08-01T12:00:00.000Z',
    status: 'scheduled',
    venue: 'PBL Arena 1',
    homeTeamId: 'khon-kaen-kings',
    awayTeamId: 'korat-thunder',
    homeScore: null,
    awayScore: null,
  },
  {
    id: 'game-104',
    slug: 'hyh-vs-ryr-week-6',
    seasonId: 'season-2026',
    week: 6,
    startsAt: '2026-08-02T13:00:00.000Z',
    status: 'scheduled',
    venue: 'PBL Arena 2',
    homeTeamId: 'hat-yai-hawks',
    awayTeamId: 'rayong-raptors',
    homeScore: null,
    awayScore: null,
  },
  {
    id: 'game-097',
    slug: 'ptp-vs-bbz-week-5',
    seasonId: 'season-2026',
    week: 5,
    startsAt: '2026-07-26T13:00:00.000Z',
    status: 'final',
    venue: 'PBL Arena 1',
    homeTeamId: 'pattaya-pulse',
    awayTeamId: 'bangkok-blaze',
    homeScore: 78,
    awayScore: 84,
  },
  {
    id: 'game-098',
    slug: 'cmc-vs-kkg-week-5',
    seasonId: 'season-2026',
    week: 5,
    startsAt: '2026-07-25T12:00:00.000Z',
    status: 'final',
    venue: 'PBL Arena 2',
    homeTeamId: 'chiang-mai-cloud',
    awayTeamId: 'khon-kaen-kings',
    homeScore: 91,
    awayScore: 86,
  },
  {
    id: 'game-099',
    slug: 'ryr-vs-pkw-week-5',
    seasonId: 'season-2026',
    week: 5,
    startsAt: '2026-07-24T13:30:00.000Z',
    status: 'final',
    venue: 'PBL Arena 1',
    homeTeamId: 'rayong-raptors',
    awayTeamId: 'phuket-waves',
    homeScore: 71,
    awayScore: 96,
  },
  {
    id: 'game-100',
    slug: 'krt-vs-hyh-week-5',
    seasonId: 'season-2026',
    week: 5,
    startsAt: '2026-07-23T12:00:00.000Z',
    status: 'final',
    venue: 'PBL Arena 2',
    homeTeamId: 'korat-thunder',
    awayTeamId: 'hat-yai-hawks',
    homeScore: 82,
    awayScore: 88,
  },
];

export const demoNews: NewsPost[] = [
  {
    id: 'news-1',
    slug: 'season-2026-midseason-report',
    title: 'Midseason report: the title race is wide open',
    excerpt: 'Eight teams, four weeks remaining and no easy path to the PBL Finals.',
    content: 'The 2026 season has reached its turning point. Phuket Waves currently lead the West, while Bangkok Blaze and Chiang Mai Cloud continue to trade wins in the East. With four weeks remaining, every possession now affects playoff seeding.\n\nThe next slate features two major tests: Blaze versus Cloud and Waves versus Pulse. Both games will be streamed live through the official league channels.',
    category: 'League',
    publishedAt: '2026-07-27T09:00:00.000Z',
    authorName: 'PBL Media',
    featured: true,
    accent: '#ff6b22',
  },
  {
    id: 'news-2',
    slug: 'wave-rin-player-of-the-week',
    title: 'Wave Rin earns Player of the Week',
    excerpt: 'The Phuket guard averaged 31 points and 12 assists across two victories.',
    content: 'Wave Rin controlled the pace in both of Phuket\'s victories this week. The point guard combined efficient scoring with patient playmaking, creating open looks throughout both matchups.\n\nRin currently leads the league in assists and sits second in points per game.',
    category: 'Awards',
    publishedAt: '2026-07-25T10:30:00.000Z',
    authorName: 'Stats Desk',
    featured: true,
    accent: '#00cfa6',
  },
  {
    id: 'news-3',
    slug: 'week-six-schedule',
    title: 'Week 6 schedule and broadcast guide',
    excerpt: 'Four games, two arenas and a crucial battle at the top of the East.',
    content: 'Week 6 tips off with Bangkok Blaze hosting Chiang Mai Cloud. Phuket Waves then welcome Pattaya Pulse before the weekend doubleheader.\n\nMatch times and stream links can change. Check the Games page before tip-off for the latest information.',
    category: 'Schedule',
    publishedAt: '2026-07-23T08:00:00.000Z',
    authorName: 'PBL Media',
    featured: false,
    accent: '#4a7dff',
  },
  {
    id: 'news-4',
    slug: 'rookie-watch-storm-sak',
    title: 'Rookie watch: Storm Sak is finding another gear',
    excerpt: 'Korat’s young scorer is turning difficult shots into a weekly highlight reel.',
    content: 'Storm Sak has become one of the season\'s most exciting scorers. His confidence has grown each week, and Korat now trusts him to create late in the shot clock.\n\nThe next step is consistency on defense, where his length can change possessions.',
    category: 'Players',
    publishedAt: '2026-07-20T11:00:00.000Z',
    authorName: 'PBL Media',
    featured: false,
    accent: '#8f7cff',
  },
  {
    id: 'news-5',
    slug: 'community-night-announced',
    title: 'PBL Community Night announced for August 8',
    excerpt: 'Join players, staff and creators for an open run and skills challenge.',
    content: 'Community Night returns on August 8 with an open run, shooting contests and meet-and-greet sessions. Registration details will be posted in the official Discord server.\n\nThe event is free and open to all community members.',
    category: 'Community',
    publishedAt: '2026-07-18T07:30:00.000Z',
    authorName: 'Community Team',
    featured: false,
    accent: '#ff4f91',
  },
];

export const demoAccolades: Accolade[] = [
  {
    id: 'award-1',
    season: '2026',
    title: 'Midseason MVP',
    recipient: 'Wave Rin',
    teamId: 'phuket-waves',
    description: 'League-leading playmaking with elite scoring efficiency.',
    type: 'award',
  },
  {
    id: 'award-2',
    season: '2026',
    title: 'Defensive Player',
    recipient: 'Ocean Max',
    teamId: 'phuket-waves',
    description: 'Controls the paint with 2.7 blocks and 13.6 rebounds per game.',
    type: 'award',
  },
  {
    id: 'record-1',
    season: '2026',
    title: 'Single-game assists',
    recipient: 'Mint Velocity — 18 AST',
    teamId: 'bangkok-blaze',
    description: 'Set against Korat Thunder in Week 3.',
    type: 'record',
  },
  {
    id: 'record-2',
    season: '2026',
    title: 'Single-game points',
    recipient: 'Kai Nova — 47 PTS',
    teamId: 'bangkok-blaze',
    description: 'Set against Pattaya Pulse in Week 5.',
    type: 'record',
  },
];

export const demoStaff: StaffMember[] = [
  { id: 'staff-1', name: 'Peerapat P.', role: 'Commissioner', department: 'League Office', robloxUsername: 'PBLCommissioner' },
  { id: 'staff-2', name: 'Narin K.', role: 'Head Statistician', department: 'Competition', robloxUsername: 'NarinStats' },
  { id: 'staff-3', name: 'Mali S.', role: 'Content Director', department: 'Media', robloxUsername: 'MaliCreates' },
  { id: 'staff-4', name: 'Beam T.', role: 'Community Manager', department: 'Community', robloxUsername: 'BeamPBL' },
  { id: 'staff-5', name: 'Jay R.', role: 'Broadcast Producer', department: 'Media', robloxUsername: 'JayOnAir' },
];

export const demoLinks: LeagueLink[] = [
  { id: 'link-1', label: 'Roblox Group', description: 'Join the official PBL community group.', href: 'https://www.roblox.com/groups', kind: 'community' },
  { id: 'link-2', label: 'Practical Basketball', description: 'Enter the official league experience.', href: 'https://www.roblox.com/games', kind: 'game' },
  { id: 'link-3', label: 'Discord Server', description: 'Schedules, tryouts, support and live discussion.', href: 'https://discord.com/', kind: 'community' },
  { id: 'link-4', label: 'YouTube', description: 'Live broadcasts, highlights and weekly recaps.', href: 'https://www.youtube.com/', kind: 'social' },
];

export const demoSiteData: SiteData = {
  source: 'demo',
  season: demoSeasons[0],
  seasons: demoSeasons,
  teams: demoTeams,
  players: demoPlayers,
  games: demoGames,
  news: demoNews,
  accolades: demoAccolades,
  staff: demoStaff,
  links: demoLinks,
};

