'use client';

import { useTranslations } from 'next-intl';
import type { PlayerSeasonHistory, TeamSeasonHistory } from '@/lib/league-history';

export function PlayerSeasonHistoryTable({ entries }: { entries: PlayerSeasonHistory[] }) {
  const t = useTranslations('Profile');
  return <section className="race-panel mt-14 overflow-hidden rounded-[1.5rem] sm:mt-16"><div className="border-b border-[var(--line)] px-5 py-5"><p className="race-eyebrow">PROFILE DATA</p><h2 className="race-display mt-2 text-3xl">{t('seasonHistory')}</h2><p className="mt-2 text-sm text-[var(--ink-soft)]">{t('seasonHistoryBody')}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[35rem]"><thead><tr className="border-b border-[var(--line)] text-left text-[.6rem] font-black uppercase tracking-[.1em] text-[var(--ink-faint)]"><th className="px-5 py-3">{t('season')}</th><th className="px-3 py-3 text-center">{t('games')}</th><th className="px-3 py-3 text-center">{t('points')}</th><th className="px-3 py-3 text-center">{t('rebounds')}</th><th className="px-5 py-3 text-center">{t('assists')}</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.seasonId} className="border-b border-[var(--line)] last:border-0"><td className="px-5 py-4 font-black uppercase italic">{entry.seasonName}</td><td className="px-3 py-4 text-center font-bold text-[var(--ink-soft)]">{entry.games}</td><td className="px-3 py-4 text-center font-black">{entry.points.toFixed(1)}</td><td className="px-3 py-4 text-center font-black">{entry.rebounds.toFixed(1)}</td><td className="px-5 py-4 text-center font-black">{entry.assists.toFixed(1)}</td></tr>)}</tbody></table></div></section>;
}

export function TeamSeasonHistoryTable({ entries }: { entries: TeamSeasonHistory[] }) {
  const t = useTranslations('Profile');
  return <section className="race-panel mt-14 overflow-hidden rounded-[1.5rem] sm:mt-16"><div className="border-b border-[var(--line)] px-5 py-5"><p className="race-eyebrow">TEAM DATA</p><h2 className="race-display mt-2 text-3xl">{t('seasonHistory')}</h2><p className="mt-2 text-sm text-[var(--ink-soft)]">{t('seasonHistoryBody')}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[28rem]"><thead><tr className="border-b border-[var(--line)] text-left text-[.6rem] font-black uppercase tracking-[.1em] text-[var(--ink-faint)]"><th className="px-5 py-3">{t('season')}</th><th className="px-3 py-3 text-center">{t('record')}</th><th className="px-5 py-3 text-center">WIN %</th></tr></thead><tbody>{entries.map((entry) => { const pct = entry.wins + entry.losses ? entry.wins / (entry.wins + entry.losses) : 0; return <tr key={entry.seasonId} className="border-b border-[var(--line)] last:border-0"><td className="px-5 py-4 font-black uppercase italic">{entry.seasonName}</td><td className="px-3 py-4 text-center font-black">{entry.wins}–{entry.losses}</td><td className="px-5 py-4 text-center font-black">{pct.toFixed(3).replace(/^0/, '')}</td></tr>; })}</tbody></table></div></section>;
}
